name: Easy GSI..

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://assorted.downloads.oppo.com/firmware/CPH1871Q/CPH1875EUEX_11_OTA_3120_all_1LdyQsmIpxeb.ozip   
  ROM_NAME: ColorOS
  ZIP_NAME: FindX-CPH1875EUEX_11_F.12
  erfanrepo: https://github.com/Area69Lab/ErfanGSIs.git 
  TZ: Asia/Kolkata
  username : KaanDikec
  password : hrdNiDBqbHo7
  uploadto : uploads.androidfilehost.com
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@v2
       
       - name: Clean Up
         run: |
           
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean 
           
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules $erfanrepo
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: sudo ./ErfanGSIs/url2GSI.sh $ROM_URL $ROM_NAME
       
       - name: Zip Aonly and upload 
         run: |
              mkdir final
              sudo chmod -R 777 ErfanGSIs/output
              cd ErfanGSIs/output
              zip -r $ZIP_NAME-GSI-Aonly.7z *-Aonly-*.img
              curl -T $ZIP_NAME-GSI-Aonly.7z ftp://$username:$password@$uploadto/          
       - name: Zip AB and upload 
         run: |
              cd ErfanGSIs/output
              zip -r $ZIP_NAME-GSI-AB.7z *-AB-*.img
              curl -T $ZIP_NAME-GSI-AB.7z ftp://$username:$password@$uploadto/          
       - name: mirror for sourceforge
         uses: wlixcc/SFTP-Deploy-Action@v1.0
         with:
           username: 'kaandikec'
           server: 'frs.sourceforge.net'
           ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
           local_path: 'ErfanGSIs/output/'
           remote_path: '/home/pfs/project/kaan-gsi'
           args: '-o ConnectTimeout=5'
       - name: Print build info
         run: |
              cat ErfanGSIs/output/*-Aonly-*.txt
         
            
